- name: Documentación de Docker
  href: index.yml
- name: Guía de inicio rápido
  items:
    - name: Implementación de una máquina virtual Ubuntu con Docker
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
  expanded: true
- name: Tutoriales
  items:
    - name: Aplicación web Python con Docker y PostgreSQL
      href: ../app-service/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'Integración y entrega continuas con Docker, Jenkins y Linux'
      href: /azure/developer/jenkins/pipeline-with-github-and-docker
- name: Guías paso a paso
  items:
    - name: Extensión de máquina virtual de Docker
      href: 'https://github.com/Azure/azure-docker-extension/blob/master/README.md'
    - name: Registro de contenedor de Docker
      href: ../container-registry/container-registry-get-started-portal.md
- name: Recursos
  items:
    - name: Azure Roadmap
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Controlador de Azure de Docker
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Sitio de Azure de Docker
      href: 'https://docs.docker.com/cloud/aci-integration/'
    - name: Sitio de Docker
      href: 'https://docker.com'