### YamlMime:FAQ
metadata:
  title: 'Solución de problemas de las unidades administrativas y Preguntas frecuentes: Azure Active Directory | Microsoft Docs'
  description: Investigue las unidades administrativas para conceder permisos con ámbito restringido en Azure Active Directory
  services: active-directory
  documentationcenter: ''
  author: rolyon
  manager: daveba
  ms.service: active-directory
  ms.topic: how-to
  ms.subservice: roles
  ms.workload: identity
  ms.date: 11/04/2020
  ms.author: rolyon
  ms.reviewer: anandy
  ms.custom: oldportal;it-pro;
  ms.collection: M365-identity-device-management
  ms.openlocfilehash: 7577d738de6dc7933a4d884879eed4bf9614eadf
  ms.sourcegitcommit: 8b38eff08c8743a095635a1765c9c44358340aa8
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 06/30/2021
  ms.locfileid: "113095330"
title: 'Unidades administrativas de Azure AD: Solución de problemas y preguntas frecuentes'
summary: >
  Para un control administrativo más pormenorizado en Azure Active Directory (Azure AD), puede asignar a los usuarios un rol de Azure AD con un ámbito limitado a una o varias unidades administrativas. Para obtener scripts de PowerShell de ejemplo para tareas comunes, consulte [Uso de unidades administrativas para trabajar](/powershell/azure/active-directory/working-with-administrative-units).
sections:
- name: Omitido
  questions:
  - question: >
      ¿Por qué no puedo crear una unidad administrativa?
    answer: >
      Solo un *administrador global* o un *administrador de rol con privilegios* puede crear una unidad administrativa en Azure AD. Compruebe que el usuario que intenta crear la unidad administrativa tenga asignado el rol de *administrador global* o de *administrador de rol con privilegios*.
  - question: >
      He agregado un grupo a una unidad administrativa. ¿Por qué todavía no aparecen los miembros del grupo?
    answer: >
      Al agregar un grupo a una unidad administrativa, no todos los miembros del grupo se agregan a esta. Los usuarios deben asignarse directamente a la unidad administrativa.
  - question: >
      Acabo de agregar (o quitar) un miembro de la unidad administrativa. ¿Por qué no se muestra (o se sigue mostrando) en la interfaz de usuario?
    answer: >
      A veces, la adición o eliminación de uno o varios miembros de una unidad administrativa puede tardar unos minutos antes de que se refleje en el panel **Unidades administrativas**. También puede ir directamente a las propiedades del recurso asociado y ver si se ha completado la acción. Para más información sobre los usuarios y grupos de las unidades administrativas, consulte [Visualización de una lista de unidades administrativas para un usuario](admin-units-add-manage-users.md) y [Visualización de una lista de unidades administrativas para un grupo](admin-units-add-manage-groups.md).
  - question: >
      Soy administrador de contraseñas delegado de una unidad administrativa. ¿Por qué no puedo restablecer la contraseña de un usuario específico?
    answer: "Como administrador de una unidad administrativa, solo puede restablecer las contraseñas de los usuarios asignados a la unidad administrativa. Asegúrese de que el usuario para el que se produjo el error de restablecimiento de contraseña pertenece a la unidad administrativa a la que se le asignó. Si el usuario pertenece a la misma unidad administrativa y todavía no puede restablecer su contraseña, compruebe los roles que tiene asignados. \n\nPara evitar una elevación de privilegios, un administrador con ámbito de unidad administrativa no puede restablecer la contraseña de un usuario asignado a un rol con un ámbito de toda la organización.\n"
  - question: >
      ¿Por qué son necesarias las unidades administrativas? ¿No podrían usarse grupos de seguridad para definir un ámbito?
    answer: "Los grupos de seguridad tienen un propósito y modo de autorización existentes. Un *administrador de usuarios*, por ejemplo, puede administrar la pertenencia a todos los grupos de seguridad de la organización de Azure AD. El rol podría usar grupos para administrar el acceso a aplicaciones como Salesforce. Un *administrador de usuarios* no debe poder administrar el modelo de delegación, que sucedería si los grupos de seguridad se ampliaran para admitir escenarios de \"agrupación de recursos\". \n\nLas unidades administrativas, como las unidades organizativas en Windows Server Active Directory, están diseñadas para proporcionar una manera de administrar con ámbito una amplia gama de objetos de directorio. Los grupos de seguridad pueden ser miembros de los ámbitos de recursos. El uso de grupos de seguridad para definir el conjunto de grupos de seguridad que un administrador puede administrar podría resultar confuso.\n"
  - question: >
      ¿Por qué se agrega un grupo a una unidad administrativa?
    answer: >
      Al agregar un grupo a una unidad administrativa, el grupo se coloca en el ámbito de administración de cualquier *administrador de usuarios* cuyo ámbito también sea esa unidad administrativa. Los administradores de usuarios de la unidad administrativa pueden administrar el nombre y la pertenencia del grupo. No se concede al *administrador de usuarios* ningún permiso para administrar los usuarios del grupo (por ejemplo, restablecer sus contraseñas). Para conceder al *administrador de usuario* la capacidad de administrar usuarios, estos deben ser miembros directos de la unidad administrativa.
  - question: >
      ¿Un recurso (usuario o grupo) puede ser miembro de más de una unidad administrativa?
    answer: >
      Sí, un recurso puede ser miembro de más de una unidad administrativa. Los administradores con ámbito de la unidad administrativa o toda la organización que tienen permisos sobre el recurso pueden administrarlo.
  - question: >
      ¿Las unidades administrativas están disponibles en las organizaciones B2C?
    answer: >
      No, las unidades administrativas no están disponibles para las organizaciones B2C.
  - question: >
      ¿Se admiten las unidades administrativas anidadas?
    answer: >
      No se admiten las unidades administrativas anidadas.
  - question: >
      ¿Las unidades administrativas son compatibles con PowerShell y Graph API?
    answer: >
      Sí. Puede encontrar la compatibilidad con las unidades administrativas en la [documentación de cmdlets de PowerShell](/powershell/module/Azuread/) y los [scripts de ejemplo](/powershell/azure/active-directory/working-with-administrative-units).


      La compatibilidad con el [tipo de recurso administrativeUnit](/graph/api/resources/administrativeunit) puede encontrarla en Microsoft Graph.
additionalContent: "\n## <a name=\"next-steps\"></a>Pasos siguientes\n\n- [Restricción del ámbito de los roles mediante las unidades administrativas](administrative-units.md)\n- [Administración de unidades administrativas](admin-units-manage.md)"
