### YamlMime:FAQ
metadata:
  title: Preguntas frecuentes acerca de la implementación de Azure App Service | Microsoft Docs
  description: Conozca las respuestas a las preguntas más frecuentes sobre la implementación en la característica Web Apps de Azure App Service.
  author: genlin
  manager: dcscontentpm
  tags: top-support-issue
  ms.assetid: 2fa5ee6b-51a6-4237-805f-518e6c57d11b
  ms.topic: article
  ms.service: app-service
  ms.date: 11/01/2018
  ms.author: genli
  ms.custom: seodec18
  ms.openlocfilehash: 58b42f672389a13342d09cf796204906987e48b8
  ms.sourcegitcommit: 05dd6452632e00645ec0716a5943c7ac6c9bec7c
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 08/17/2021
  ms.locfileid: "122253230"
title: Preguntas más frecuentes sobre la implementación en Web Apps en Azure
summary: >
  En este artículo se proporcionan las respuestas a las preguntas más frecuentes sobre los problemas relacionados con la implementación en la [característica Web Apps de Azure App Service](https://azure.microsoft.com/services/app-service/web/).


  [!INCLUDE [support-disclaimer](../../includes/support-disclaimer.md)]
sections:
- name: Omitido
  questions:
  - question: >
      Acabo de empezar a usar aplicaciones web de App Service. ¿Cómo publico el código?
    answer: >
      Aquí tiene algunas opciones para publicar código de aplicaciones web:


      *   Realice la implementación con Visual Studio. Si dispone de la solución de Visual Studio, haga clic con el botón derecho en el proyecto de aplicación web y seleccione **Publicar**.

      *   Realice la implementación mediante un cliente FTP. En Azure Portal, descargue el perfil de publicación para la aplicación web en la que quiere implementar el código. Después, cargue los archivos en \site\wwwroot con las mismas credenciales FTP del perfil de publicación.


      Para obtener más información, vea cómo [implementar la aplicación en App Service](deploy-local-git.md).
  - question: >
      Veo un mensaje de error al intentar implementar desde Visual Studio. ¿Cómo se resuelve este problema?
    answer: "Si ve el mensaje siguiente, es posible que esté usando una versión antigua del SDK: \"Error durante la implementación para el recurso 'YourResourceName' del grupo de recursos 'YourResourceGroup': MissingRegistrationForLocation. La suscripción no está registrada para el tipo de recurso 'componentes' en la ubicación 'Centro de EE. UU.'. Vuelva a registrar este proveedor a fin de obtener acceso a esta ubicación\". \n\nPara resolver este error, actualice al [SDK más reciente](https://azure.microsoft.com/downloads/). Si ve este mensaje y tiene el SDK más reciente, envíe una solicitud de soporte técnico.\n"
  - question: >
      ¿Cómo se implementa una aplicación ASP.NET de Visual Studio en App Service?
    answer: >
      <a id="deployasp"></a>


      En el tutorial [Creación de una aplicación web ASP.NET en Azure](quickstart-dotnetcore.md) se muestra cómo implementar una aplicación web ASP.NET en una aplicación web en App Service mediante Visual Studio 2017.
  - question: >
      ¿Cuáles son los distintos tipos de credenciales de implementación?
    answer: >
      App Service admite dos tipos de credenciales para la implementación de GIT local y la implementación FTP/S. Para obtener más información sobre cómo configurar las credenciales de implementación, vea [Configuración de credenciales de implementación para App Service](deploy-configure-credentials.md).
  - question: >
      ¿Cuál es la estructura de archivos o directorios de mi aplicación web de App Service?
    answer: >
      Para obtener información sobre la estructura de archivos de la aplicación de App Service, vea [File structure in Azure](https://github.com/projectkudu/kudu/wiki/File-structure-on-azure) (Estructura de archivos en Azure).
  - question: >
      ¿Cómo puedo resolver el error FTP 550 "Espacio insuficiente en el disco" al intentar usar FTP con mis archivos?
    answer: >
      Si ve este mensaje, es probable que se haya topado con una cuota de disco en el plan de servicio de la aplicación web. Tal vez necesite escalar verticalmente a un nivel de servicio superior, en función de sus necesidades de espacio en disco. Para obtener más información sobre los planes de precios y los límites de recursos, vea [Precios de App Service](https://azure.microsoft.com/pricing/details/app-service/).
  - question: >
      ¿Cómo se configura la implementación continua para la aplicación web de App Service?
    answer: >
      Puede configurar la implementación continua desde varios recursos, incluidos Azure DevOps, OneDrive, GitHub, Bitbucket, Dropbox y otros repositorios de GIT. Estas opciones están disponibles en el portal. El tutorial [Implementación continua en App Service](deploy-continuous-deployment.md) es un recurso muy útil en el que se explica cómo se configura la implementación continua.
  - question: >
      ¿Cómo se solucionan los problemas relacionados con la implementación continua desde GitHub y Bitbucket?
    answer: >
      Para ayudar a investigar los problemas vinculados a la implementación continua desde GitHub o Bitbucket, vea [Investigating continuous deployment](https://github.com/projectkudu/kudu/wiki/Investigating-continuous-deployment) (Investigar la implementación continua).
  - question: >
      No puedo usar FTP con mi sitio y publicar mi código. ¿Cómo se resuelve este problema?
    answer: >
      Para solucionar problemas de FTP:


      1. Compruebe que el nombre de host y las credenciales que ha especificado sean correctos. Para obtener información detallada sobre los distintos tipos de credenciales y cómo usarlas, vea [Deployment credentials](https://github.com/projectkudu/kudu/wiki/Deployment-credentials) (Credenciales de implementación).

      2. Compruebe que los puertos FTP no estén bloqueados por un firewall. Los puertos deben tener estos valores de configuración:
          * Puerto de conexión de control de FTP: 21
          * Puerto de conexión de datos de FTP: 989, 10001-10300
  - question: >
      ¿Cómo publico mi código en App Service?
    answer: >
      El inicio rápido de Azure está diseñado para ayudarle a implementar la aplicación mediante el uso de la pila de implementación y el método que elija. Para utilizar Inicio rápido, en Azure Portal, vaya al servicio de aplicación en **Implementación** y seleccione **Inicio rápido**.
  - question: >
      ¿Por qué mi aplicación se reinicia a veces después de la implementación en App Service?
    answer: >
      Para obtener información sobre las circunstancias en las que una implementación de aplicación podría producir un reinicio, vea [Deployment vs. runtime issues](https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues#deployments-and-web-app-restarts") (Problemas de implementación frente a problemas en tiempo de ejecución). Como se describe en el artículo, App Service implementa los archivos en la carpeta wwwroot. Nunca reinicia directamente la aplicación.
  - question: >
      ¿Cómo se puede integrar código de Azure DevOps con App Service?
    answer: "Tiene dos opciones para usar la implementación continua con Azure DevOps:\n\n*   Use un proyecto de GIT. Conéctese a través de App Service mediante el centro de implementación.\n*   Use un proyecto de Control de versiones de Team Foundation (TFVC). Realice la implementación mediante el agente de compilación para App Service.\n\nLa implementación de código continua para ambas opciones depende de los flujos de trabajo de desarrollador existentes y de los procedimientos de inserción en el repositorio. Para obtener más información, consulte estos artículos: \n\n*   [Aplicar una implementación continua de la aplicación en un sitio web de Azure](https://www.visualstudio.com/docs/release/examples/azure/azure-web-apps-from-build-and-release-hubs)\n*   [Configurar una organización de Azure DevOps para que pueda implementarse en una aplicación web](https://github.com/projectkudu/kudu/wiki/Setting-up-a-VSTS-account-so-it-can-deploy-to-a-Web-App)\n"
  - question: >
      ¿Cómo se usa FTP o FTPS para implementar la aplicación en App Service?
    answer: Para obtener información sobre el uso de FTP o FTPS para implementar la aplicación web en App Service, vea [Implementación de la aplicación en App Service mediante FTP/S](deploy-ftp.md).
